---
- name: Configuração inicial dos servidores
  hosts: servidores
  become: yes

  tasks:
    - name: Atualizar pacotes no Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Atualizar pacotes no CentOS/RHEL
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Instalar utilitários essenciais
      package:
        name:
          - curl
          - git
          - vim
        state: present
